/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CustomerId = Principal;
export interface Order {
  'isCompleted' : boolean,
  'customer' : CustomerId,
  'roomNumber' : RoomNumber,
  'timestamp' : Time,
  'quantity' : Quantity,
  'products' : Array<Product>,
}
export type OrderId = bigint;
export interface Product { 'id' : ProductId, 'name' : ProductName }
export type ProductId = bigint;
export type ProductName = string;
export type Quantity = bigint;
export type RoomNumber = string;
export interface StockItem { 'inStock' : boolean, 'product' : Product }
export type Time = bigint;
export interface UserProfile { 'name' : string, 'roomNumber' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateStockItem' : ActorMethod<[Product, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeOrder' : ActorMethod<[OrderId], OrderId>,
  'getAllCurrentOrders' : ActorMethod<[], Array<Order>>,
  'getAllStockItems' : ActorMethod<[], Array<StockItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getStockStatus' : ActorMethod<[ProductId], boolean>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Array<Product>, Quantity, RoomNumber], OrderId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];